version: "3.8"

services:
  budget-app:
    build:  # Build the image from the current directory's Dockerfile
      context: .
      dockerfile: Dockerfile
    tty: true # Keep the TTY on so that the terminal works correctly  
    ports:
      - "3000:3000" # Map port 3000 on the host to port 3000 in the container
    volumes:
      - .:/app # Mount the project directory on the host to /app in the container